name: CI - OnCommit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test 1
        run: sed -i '' 's|<script type="module" crossorigin src="/assets|<script type="module" crossorigin src="./assets|g' dist/index.html
      - name: Test 1
        run: sed -i '' 's|<link rel="stylesheet" crossorigin href="/assets|<link rel="stylesheet" crossorigin href="./assets|g' dist/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
